### ISSUE TITLE
Toc component can not normal display

### ISSUE THREAD

**Issue by lhz960904** [ulivz/vuepress-theme-blog#7]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

- [x] I prepared a reproduction repo, here is the reproduction repo: [https://ihaoze.me/2019/06/27/sort-by-js/](https://ihaoze.me/2019/06/27/sort-by-js/)

- [x] This issue doesn't need a reproduction repro, here is the steps to reproduce

#### What is expected?

expected normal display

#### What is actually happening?

Misplaced display

#### Other relevant information

I think the reason is css calc css variable does not exist.
```css
   width: $tocWidth;
   padding: $sidebarTop5rem 0;
```

- `npx vuepress info`:

```
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 11.13.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: Not Found
    Safari: 12.1.1
  npmPackages:
    @vuepress/core:  1.0.2
    @vuepress/theme-default:  1.0.2
    vuepress: 1.0.2 => 1.0.2
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by newsbielt703** [comment]
I face the same issue.

 It can't normal display on production while locally on dev it works fine. 

@ulivz Will you fix it ? Or I can make a pr.

**Comment by ulivz** [comment]
@newsbielt703 Welcome to submit a pull request to help me to fix it, Thanks!

Since VuePress has been become bigger and bigger, and my own energy is limited, in order to better development, we really need to create a team and welcome to join us.
